name: haskell-torch
channels:
  - pytorch
  - conda-forge
dependencies:
  # NB tornado<6, required for jupyter, needs python=3.6
  - python=3.6
  - pytorch=1.5.0
  - numpy
  - gmp
  - libmatio
  - hdf5
  - imagemagick
  - libiconv
  - libpng
  - matplotlib
  - tensorboard
  - tensorflow
  - cudatoolkit=10.1
  - torchvision
  # These are only required for jupyter & IHaskell
  - jupyter==1.0.0
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - ipykernel
  - ipywidgets==7.1.1
  - jupyter_client==5.2.2
  - jupyter_console==5.2.0
  - jupyter_core==4.5.0
  - tornado<6
  - jupyterlab
