name: haskell-torch
channels:
  - pytorch
  - conda-forge
dependencies:
  # NB tornado<6, required for jupyter, needs python=3.6
  - python=3.6
  - pytorch=1.5.0
  - numpy
  - gmp
  - libmatio
  - hdf5
  - imagemagick
  - libiconv
  - libpng
  - matplotlib
  - tensorboard
  - tensorflow
  - cudatoolkit=10.1
  - torchvision
  # These are only required for jupyter & IHaskell
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - ipykernel
  - ipywidgets
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - nb_conda_kernels
  - nodejs
  - ncurses
