name:                haskell-torch-matio
version:             0.5
github:              "abarbu/haskell-torch"
license:             BSD3
author:              "Andrei Barbu"
maintainer:          "andrei@0xab.com"
copyright:           "2018 Andrei Barbu"
homepage:            https://github.com/abarbu/haskell-torch
bug-reports:         https://github.com/abarbu/haskell-torch/issues
category:            Foreign
synopsis:            Manipulate Matlab .mat files with matio

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/abarbu/haskell-torch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  extra-libraries:
    - matio
  dependencies:
    - inline-c
    - inline-c-cpp
    - containers
    - text
    - bytestring
    - aeson
    - half
    - vector
    - extra
    - directory
    - filepath
    - ieee754
    - template-haskell
