name:                haskell-torch-datasets
version:             0.8.0.0
github:              "abarbu/haskell-torch"
license:             BSD3
author:              "Andrei Barbu"
maintainer:          "andrei@0xab.com"
copyright:           "2018 Andrei Barbu"
homepage:            https://github.com/abarbu/haskell-torch
bug-reports:         https://github.com/abarbu/haskell-torch/issues
category:            AI
synopsis:            Deep learning in Haskell on top of Torch and PyTorch

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/abarbu/haskell-torch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - haskell-torch
    - haskell-torch-imagemagick
    - haskell-torch-matio
    - haskell-torch-tensorboard-proto
    - aeson
    - array
    - binary
    - bytestring
    - containers
    - data-default
    - directory
    - extra
    - filepath
    - generics-eot
    - ghc-typelits-knownnat
    - ghc-typelits-natnormalise
    - half
    - hashable
    - hashtables
    - haskell-src-exts
    - haskell-src-meta
    - hostname
    - ieee754
    - interpolateIO
    - matplotlib
    - megaparsec
    - microlens
    - monad-control
    - monad-loops
    - mtl
    - parser-combinators
    - pipes
    - pipes-aeson
    - pipes-bytestring
    - pipes-concurrency
    - pipes-csv
    - pipes-extras
    - pipes-group
    - pipes-parse
    - pipes-safe
    - proto-lens
    - random
    - safe-exceptions
    - shelly
    - singletons
    - statistics
    - string-qq
    - syb
    - template-haskell
    - text
    - time
    - unix
    - vector
    - yaml
    - zlib
    - monad-logger
    - docopt
    - default-type-plugin
    - simplify-nat-algebra-plugin
    - temporary
    - generics-sop
    - deepseq
    - ghc-prim
    - barbies
    - vector-algorithms
    - prettyprinter
